version: '3.8'

services:
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cesfam-frontend-local
    ports:
      - "80:8080"
    depends_on:
      - backend
    restart: always
    networks:
      - red_publica
      - red_backend

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cesfam-backend-local
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://cesfam_user@database:5432/cesfam
      - DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - database
    restart: always
    networks:
      - red_backend
      - red_db

  database:
    image: postgres:15-alpine
    container_name: cesfam-database-local
    environment:
      - POSTGRES_DB=cesfam
      - POSTGRES_USER=cesfam_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata_local:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    networks:
      - red_db

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: cesfam-prometheus-local
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    depends_on:
      - backend
    networks:
      - red_monitoring
      - red_backend

  grafana:
    image: grafana/grafana:10.0.3
    container_name: cesfam-grafana-local
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANONYMOUS_ENABLED=true
      - GF_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
    networks:
      - red_monitoring

volumes:
  pgdata_local:
  prometheus_data:
  grafana_data:

networks:
  red_publica:
  red_backend:
    internal: true
  red_db:
    internal: true
  red_monitoring:
    # Quitamos internal: true en caso de que grafana necesite cargar mapas o assets de internet.
    # Además grafana está exponiendo puerto 3000 al exterior.

secrets:
  db_password:
    file: ./secrets/db_password.txt
