services:
  cesfam-backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cesfam-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
      # Reemplazar con la URL real de conexión a la base de datos en producción
      - DATABASE_URL=postgres://cesfam_user:cesfam_secure_password@db-host:5432/cesfam
    restart: always
